// <auto-generated />
using System;
using LocalMateAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalMateAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925235025_AddSubscriptionPhase1")]
    partial class AddSubscriptionPhase1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("EstimatedCostMax")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("EstimatedCostMin")
                        .HasColumnType("numeric(12,0)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CuratedItineraries");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuratedItineraryId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("CuratedItineraryId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("CuratedItineraryItems");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuickTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_Feedbacks_TripId");

                    b.HasIndex("UserId", "TripId")
                        .IsUnique()
                        .HasDatabaseName("UX_Feedbacks_UserId_TripId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.ItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("numeric(12,0)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.MetroStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("MetroStations");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,0)");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("ProviderOrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderOrderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentOrders_ProviderOrderCode");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentOrders", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedCostMax")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("EstimatedCostMin")
                        .HasColumnType("numeric(12,0)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItineraryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("QuickTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryItemId");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_PlaceReviews_PlaceId");

                    b.HasIndex("UserId", "ItineraryItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_PlaceReviews_UserId_ItineraryItemId");

                    b.ToTable("PlaceReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlaceReviews_QuickTags_AllowedValues", "\"QuickTags\" <@ ARRAY['WorthVisiting', 'NearMetro', 'EasyToReach', 'GoodValue', 'NiceAtmosphere', 'GoodForGroups', 'TooCrowded', 'HardToFind', 'Overpriced', 'BelowExpectations', 'InaccurateDescription', 'WantsReplacement']::text[]");

                            t.HasCheckConstraint("CK_PlaceReviews_QuickTags_MaxThree", "cardinality(\"QuickTags\") <= 3");

                            t.HasCheckConstraint("CK_PlaceReviews_Rating", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceTag", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaceId", "TagId")
                        .HasName("PK_PlaceTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_PlaceTags_TagId");

                    b.ToTable("PlaceTags", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Tags_Type_Name");

                    b.ToTable("Tags", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tags_Type", "\"Type\" IN ('Interest', 'TravelStyle')");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("BudgetMin")
                        .HasColumnType("numeric(12,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.TripTag", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("TripId", "TagId")
                        .HasName("PK_TripTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_TripTags_TagId");

                    b.ToTable("TripTags", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId", "Type", "CreatedAt")
                        .HasDatabaseName("IX_UsageEvents_UserId_Type_CreatedAt");

                    b.ToTable("UsageEvents", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("User");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('User', 'Admin')");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Provider", "ProviderSubject")
                        .HasName("PK_UserExternalLogins");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("UX_UserExternalLogins_UserId_Provider");

                    b.ToTable("UserExternalLogins", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserPreferenceTag", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TagId")
                        .HasName("PK_UserPreferenceTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_UserPreferenceTags_TagId");

                    b.ToTable("UserPreferenceTags", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlanCode")
                        .IsUnique()
                        .HasDatabaseName("UX_UserSubscriptions_UserId_PlanCode");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItineraryItem", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.CuratedItinerary", "CuratedItinerary")
                        .WithMany("Items")
                        .HasForeignKey("CuratedItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuratedItinerary");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Feedbacks_Trips_TripId");

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Feedbacks_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.ItineraryItem", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.Trip", "Trip")
                        .WithMany("Items")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceReview", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.ItineraryItem", null)
                        .WithMany()
                        .HasForeignKey("ItineraryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceReviews_ItineraryItems_ItineraryItemId");

                    b.HasOne("LocalMateAI.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceReviews_Places_PlaceId");

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceReviews_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceTag", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Place", "Place")
                        .WithMany("Tags")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceTags_Places_PlaceId");

                    b.HasOne("LocalMateAI.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceTags_Tags_TagId");

                    b.Navigation("Place");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Trip", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Trips_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.TripTag", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TripTags_Tags_TagId");

                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany("Tags")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TripTags_Trips_TripId");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UsageEvent", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserExternalLogins_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserPreferenceTag", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserPreferenceTags_Tags_TagId");

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany("PreferenceTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPreferenceTags_Users_UserId");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItinerary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Place", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.User", b =>
                {
                    b.Navigation("PreferenceTags");
                });
#pragma warning restore 612, 618
        }
    }
}
