using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LocalMateAI.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class ChangeUserIdToGuid : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                ALTER TABLE "USERS"
                    ALTER COLUMN "Id" DROP IDENTITY IF EXISTS;

                ALTER TABLE "USERS"
                    ALTER COLUMN "Id" TYPE uuid
                    USING (
                        (
                            '00000000-0000-0000-' ||
                            substring(lpad(to_hex("Id"), 16, '0') from 1 for 4) ||
                            '-' ||
                            substring(lpad(to_hex("Id"), 16, '0') from 5 for 12)
                        )::uuid
                    );
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM "USERS"
                        WHERE left(replace("Id"::text, '-', ''), 16) <> '0000000000000000'
                    ) THEN
                        RAISE EXCEPTION
                            'Cannot convert USERS.Id back to bigint because UUID rows created after ChangeUserIdToGuid cannot be mapped losslessly.';
                    END IF;
                END
                $$;

                ALTER TABLE "USERS"
                    ALTER COLUMN "Id" TYPE bigint
                    USING (
                        ('x' || substring(replace("Id"::text, '-', '') from 17 for 16))::bit(64)::bigint
                    );

                ALTER TABLE "USERS"
                    ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

                SELECT setval(
                    pg_get_serial_sequence('"USERS"', 'Id'),
                    COALESCE((SELECT MAX("Id") FROM "USERS"), 1),
                    EXISTS (SELECT 1 FROM "USERS")
                );
                """);
        }
    }
}
