// <auto-generated />
using System;
using LocalMateAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalMateAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003024304_AddUnaccentExtension")]
    partial class AddUnaccentExtension
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("PaymentOrderCodeSequence");

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("EstimatedCostMax")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("EstimatedCostMin")
                        .HasColumnType("numeric(12,0)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CuratedItineraries");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuratedItineraryId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("CuratedItineraryId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("CuratedItineraryItems");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.EmailOtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("UX_EmailOtpCodes_Email_Purpose_Active")
                        .HasFilter("\"ConsumedAt\" IS NULL");

                    b.HasIndex("Email", "Purpose", "CreatedAt")
                        .HasDatabaseName("IX_EmailOtpCodes_Email_Purpose_CreatedAt");

                    b.ToTable("EmailOtpCodes", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("UX_EmailOutboxMessages_DeduplicationKey");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("IX_EmailOutboxMessages_NextAttemptAt_Pending")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("EmailOutboxMessages", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.EntitlementRepairAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReconstructionMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("SubscriptionPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PaymentOrderId")
                        .IsUnique()
                        .HasFilter("\"Outcome\" = 'Repaired'");

                    b.HasIndex("SubscriptionPeriodId");

                    b.HasIndex("PaymentOrderId", "OccurredAt", "Id");

                    b.ToTable("EntitlementRepairAudits", null, t =>
                        {
                            t.HasCheckConstraint("CK_RepairAudit_Code", "length(\"DecisionCode\") BETWEEN 1 AND 64");

                            t.HasCheckConstraint("CK_RepairAudit_Outcome", "\"Outcome\" IN ('Repaired','AlreadyGranted','NotEligible','Conflict')");

                            t.HasCheckConstraint("CK_RepairAudit_Period", "\"Outcome\" NOT IN ('Repaired','AlreadyGranted') OR \"SubscriptionPeriodId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_RepairAudit_Reason", "length(btrim(\"Reason\")) BETWEEN 1 AND 500 AND \"Reason\" = btrim(\"Reason\") AND \"Reason\" !~ '[[:cntrl:]]'");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuickTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("IX_Feedbacks_TripId");

                    b.HasIndex("UserId", "TripId")
                        .IsUnique()
                        .HasDatabaseName("UX_Feedbacks_UserId_TripId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.ItineraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("numeric(12,0)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TripId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.MetroStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("MetroStations");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid?>("CheckoutAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,0)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanVersionBinding")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("PlanVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SubscriptionPlan");

                    b.Property<long>("ProviderOrderCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"PaymentOrderCodeSequence\"')");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("SingleItineraryProductVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaidAt")
                        .HasDatabaseName("IX_PaymentOrders_PaidAt_Paid")
                        .HasFilter("\"Status\" = 'Paid'");

                    b.HasIndex("ProviderOrderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentOrders_ProviderOrderCode");

                    b.HasIndex("SingleItineraryProductVersionId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentOrders_PendingSubscriptionUser")
                        .HasFilter("\"ProductKind\" = 'SubscriptionPlan' AND \"Status\" = 'Pending'");

                    b.HasIndex("PlanId", "PlanVersionId");

                    b.HasIndex("UserId", "CheckoutAttemptId")
                        .IsUnique()
                        .HasFilter("\"ProductKind\" = 'SingleItinerary'");

                    b.HasIndex("UserId", "PlanId", "Type", "Status");

                    b.ToTable("PaymentOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentOrders_Credit", "\"CreditAmount\" >= 0 AND (\"Type\" = 'Upgrade' OR \"CreditAmount\" = 0)");

                            t.HasCheckConstraint("CK_PaymentOrders_NativeBinding", "\"PlanVersionBinding\" <> 'Native' OR (\"PlanId\" IS NOT NULL AND \"PlanVersionId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PaymentOrders_Product", "(\"ProductKind\" = 'SubscriptionPlan' AND \"PlanVersionBinding\" IS NOT NULL AND \"SingleItineraryProductVersionId\" IS NULL AND \"CheckoutAttemptId\" IS NULL) OR (\"ProductKind\" = 'SingleItinerary' AND \"Type\" = 'Purchase' AND \"SingleItineraryProductVersionId\" IS NOT NULL AND \"CheckoutAttemptId\" IS NOT NULL AND \"PlanCode\" IS NULL AND \"PlanId\" IS NULL AND \"PlanVersionId\" IS NULL AND \"PlanVersionBinding\" IS NULL)");

                            t.HasCheckConstraint("CK_PaymentOrders_Upgrade", "\"Type\" <> 'Upgrade' OR (\"ProductKind\" = 'SubscriptionPlan' AND \"PlanVersionBinding\" = 'Native' AND \"Amount\" > 0)");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrderCredit", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CalculatedCreditAmount")
                        .HasColumnType("numeric(12,0)");

                    b.Property<DateTime>("OriginalEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ReleaseProviderAmountPaid")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal?>("ReleaseProviderAmountRemaining")
                        .HasColumnType("numeric(12,0)");

                    b.Property<DateTime?>("ReleaseProviderCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ReleaseProviderRequestedAmount")
                        .HasColumnType("numeric(12,0)");

                    b.Property<string>("ReleaseProviderStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReleaseReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId", "PeriodId");

                    b.HasIndex("PeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderCredits_UnreleasedPeriod")
                        .HasFilter("\"ReleasedAt\" IS NULL");

                    b.HasIndex("OrderId", "UserId");

                    b.HasIndex("PeriodId", "UserId");

                    b.ToTable("PaymentOrderCredits", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderCredits_Amount", "\"CalculatedCreditAmount\" >= 0");

                            t.HasCheckConstraint("CK_OrderCredits_Days", "\"RemainingDays\" >= 0");

                            t.HasCheckConstraint("CK_OrderCredits_ReleaseProof", "(\"ReleasedAt\" IS NULL AND \"ReleaseProviderCheckedAt\" IS NULL AND \"ReleaseProviderStatus\" IS NULL\r\n AND \"ReleaseProviderRequestedAmount\" IS NULL AND \"ReleaseProviderAmountPaid\" IS NULL\r\n AND \"ReleaseProviderAmountRemaining\" IS NULL AND \"ReleaseReasonCode\" IS NULL) OR\r\n(\"ReleasedAt\" IS NOT NULL AND \"ReleaseProviderCheckedAt\" IS NOT NULL AND \"ReleaseProviderStatus\" IS NOT NULL\r\n AND \"ReleaseProviderRequestedAmount\" IS NOT NULL AND \"ReleaseProviderAmountPaid\" IS NOT NULL\r\n AND \"ReleaseProviderAmountRemaining\" IS NOT NULL AND \"ReleaseReasonCode\" IS NOT NULL\r\n AND \"ReleaseProviderStatus\" = 'Cancelled' AND \"ReleaseProviderRequestedAmount\" > 0\r\n AND \"ReleaseProviderAmountPaid\" = 0 AND \"ReleaseProviderAmountRemaining\" = \"ReleaseProviderRequestedAmount\"\r\n AND \"ReleaseReasonCode\" = 'provider_cancelled_no_funds'\r\n AND \"ReleaseProviderCheckedAt\" <= \"ReleasedAt\"\r\n AND \"ReleasedAt\" - \"ReleaseProviderCheckedAt\" <= interval '1 minute')");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("WebhookReceiptId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("WebhookReceiptId");

                    b.HasIndex("PaymentOrderId", "OccurredAt");

                    b.ToTable("PaymentOrderStatusHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentHistory_RealTransition", "\"FromStatus\" IS NULL OR \"FromStatus\" <> \"ToStatus\"");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentWebhookReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,0)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<long>("ProviderOrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RawPayloadPurgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RawPayloadRetainUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOrderId");

                    b.HasIndex("RawPayloadRetainUntil")
                        .HasFilter("\"RawPayload\" IS NOT NULL");

                    b.HasIndex("ProviderOrderCode", "ReceivedAt");

                    b.ToTable("PaymentWebhookReceipts", null, t =>
                        {
                            t.HasCheckConstraint("CK_WebhookReceipt_Hash", "\"RawPayloadSha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_WebhookReceipt_RawSize", "octet_length(\"RawPayload\") <= 65536");

                            t.HasCheckConstraint("CK_WebhookReceipt_RawState", "(\"RawPayload\" IS NOT NULL AND \"RawPayloadPurgedAt\" IS NULL) OR (\"RawPayload\" IS NULL AND \"RawPayloadPurgedAt\" IS NOT NULL AND \"RawPayloadPurgedAt\" >= \"RawPayloadRetainUntil\")");

                            t.HasCheckConstraint("CK_WebhookReceipt_Retention", "\"RawPayloadRetainUntil\" > \"ReceivedAt\"");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PendingRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_PendingRegistrations_Email");

                    b.ToTable("PendingRegistrations", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedCostMax")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("EstimatedCostMin")
                        .HasColumnType("numeric(12,0)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItineraryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("QuickTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryItemId");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("IX_PlaceReviews_PlaceId");

                    b.HasIndex("UserId", "ItineraryItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_PlaceReviews_UserId_ItineraryItemId");

                    b.ToTable("PlaceReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlaceReviews_QuickTags_AllowedValues", "\"QuickTags\" <@ ARRAY['WorthVisiting', 'NearMetro', 'EasyToReach', 'GoodValue', 'NiceAtmosphere', 'GoodForGroups', 'TooCrowded', 'HardToFind', 'Overpriced', 'BelowExpectations', 'InaccurateDescription', 'WantsReplacement']::text[]");

                            t.HasCheckConstraint("CK_PlaceReviews_QuickTags_MaxThree", "cardinality(\"QuickTags\") <= 3");

                            t.HasCheckConstraint("CK_PlaceReviews_Rating", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceTag", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaceId", "TagId")
                        .HasName("PK_PlaceTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_PlaceTags_TagId");

                    b.ToTable("PlaceTags", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PlanFeatures", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanFeatures_Code", "\"Code\" ~ '^[A-Z][A-Z0-9_]{0,63}$'");

                            t.HasCheckConstraint("CK_PlanFeatures_Name", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_NormalizedName");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SingleItineraryEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConsumedTripId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SingleItineraryProductVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourcePaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsumedTripId")
                        .IsUnique()
                        .HasFilter("\"ConsumedTripId\" IS NOT NULL");

                    b.HasIndex("SingleItineraryProductVersionId");

                    b.HasIndex("SourcePaymentOrderId")
                        .IsUnique();

                    b.HasIndex("SourcePaymentOrderId", "UserId");

                    b.HasIndex("UserId", "ConsumedAt", "GrantedAt", "Id");

                    b.ToTable("SingleItineraryEntitlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_SingleEntitlement_Consumption", "(\"ConsumedAt\" IS NULL AND \"ConsumedTripId\" IS NULL) OR (\"ConsumedAt\" IS NOT NULL AND \"ConsumedTripId\" IS NOT NULL AND \"ConsumedAt\" >= \"GrantedAt\")");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SingleItineraryProductVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,0)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionNumber")
                        .IsUnique();

                    b.ToTable("SingleItineraryProductVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SingleProduct_Price", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_SingleProduct_Version", "\"VersionNumber\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 29000m,
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VersionNumber = 1
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LegacyUserSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourcePaymentOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TerminatedByOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LegacyUserSubscriptionId")
                        .IsUnique()
                        .HasFilter("\"LegacyUserSubscriptionId\" IS NOT NULL");

                    b.HasIndex("SourcePaymentOrderId")
                        .IsUnique()
                        .HasFilter("\"SourcePaymentOrderId\" IS NOT NULL");

                    b.HasIndex("PlanId", "PlanVersionId");

                    b.HasIndex("SourcePaymentOrderId", "UserId");

                    b.HasIndex("TerminatedByOrderId", "UserId");

                    b.HasIndex("UserId", "PlanId", "EndsAt");

                    b.HasIndex("UserId", "StartsAt", "EndsAt");

                    b.ToTable("SubscriptionPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_Periods_Range", "\"StartsAt\" < \"EndsAt\"");

                            t.HasCheckConstraint("CK_Periods_Source", "(\"SourcePaymentOrderId\" IS NOT NULL) <> (\"LegacyUserSubscriptionId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Periods_Termination", "(\"TerminatedAt\" IS NULL) = (\"TerminatedByOrderId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntitlementPriority")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EntitlementPriority")
                        .IsUnique();

                    b.HasIndex("Id", "CurrentVersionId");

                    b.HasIndex("IsActive", "EntitlementPriority");

                    b.ToTable("SubscriptionPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Plans_Code", "\"Code\" ~ '^[A-Z][A-Z0-9_]{0,63}$'");

                            t.HasCheckConstraint("CK_Plans_Free", "\"Code\" <> 'FREE' OR (\"IsActive\" AND \"IsSystem\" AND \"EntitlementPriority\" = 0)");

                            t.HasCheckConstraint("CK_Plans_Priority", "\"EntitlementPriority\" >= 0");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<long>("FeaturePublicationTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<int?>("GenerateLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,0)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SavedTripLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SubscriptionPlanVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Versions_Duration", "\"DurationDays\" IS NULL OR \"DurationDays\" > 0");

                            t.HasCheckConstraint("CK_Versions_Generate", "\"GenerateLimit\" IS NULL OR \"GenerateLimit\" >= 0");

                            t.HasCheckConstraint("CK_Versions_Number", "\"VersionNumber\" > 0");

                            t.HasCheckConstraint("CK_Versions_Origin", "\"Origin\" IN ('Published','LegacyBaseline','LegacyReconstructed') AND (\"Origin\" <> 'Published' OR \"PublishedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Versions_Price", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Versions_Saved", "\"SavedTripLimit\" IS NULL OR \"SavedTripLimit\" >= 0");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPlanVersionFeature", b =>
                {
                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("PlanVersionId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("SubscriptionPlanVersionFeatures", null, t =>
                        {
                            t.HasCheckConstraint("CK_VersionFeatures_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Tags_Type_Name");

                    b.ToTable("Tags", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tags_Type", "\"Type\" IN ('Interest', 'TravelStyle')");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal>("BudgetMin")
                        .HasColumnType("numeric(12,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PlannedStartAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TravelMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Auto");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Trips_CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.TripTag", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("TripId", "TagId")
                        .HasName("PK_TripTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_TripTags_TagId");

                    b.ToTable("TripTags", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubscriptionPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("SubscriptionPeriodId", "Type")
                        .HasFilter("\"SubscriptionPeriodId\" IS NOT NULL");

                    b.HasIndex("SubscriptionPeriodId", "UserId");

                    b.HasIndex("UserId", "Type", "CreatedAt")
                        .HasDatabaseName("IX_UsageEvents_UserId_Type_CreatedAt");

                    b.ToTable("UsageEvents", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Users_CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Status", "\"Status\" IN ('Active', 'Locked')");
                        });
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Provider", "ProviderSubject")
                        .HasName("PK_UserExternalLogins");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("UX_UserExternalLogins_UserId_Provider");

                    b.ToTable("UserExternalLogins", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserPreferenceTag", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TagId")
                        .HasName("PK_UserPreferenceTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_UserPreferenceTags_TagId");

                    b.ToTable("UserPreferenceTags", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlanCode")
                        .IsUnique()
                        .HasDatabaseName("UX_UserSubscriptions_UserId_PlanCode");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItineraryItem", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.CuratedItinerary", "CuratedItinerary")
                        .WithMany("Items")
                        .HasForeignKey("CuratedItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuratedItinerary");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.EntitlementRepairAudit", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("PaymentOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPeriod", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Feedbacks_Trips_TripId");

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Feedbacks_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.ItineraryItem", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.Trip", "Trip")
                        .WithMany("Items")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrder", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocalMateAI.Domain.Entities.SingleItineraryProductVersion", null)
                        .WithMany()
                        .HasForeignKey("SingleItineraryProductVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanId", "PlanVersionId")
                        .HasPrincipalKey("PlanId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrderCredit", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentOrderStatusHistory", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("PaymentOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.PaymentWebhookReceipt", null)
                        .WithMany()
                        .HasForeignKey("WebhookReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PaymentWebhookReceipt", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("PaymentOrderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceReview", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.ItineraryItem", null)
                        .WithMany()
                        .HasForeignKey("ItineraryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceReviews_ItineraryItems_ItineraryItemId");

                    b.HasOne("LocalMateAI.Domain.Entities.Place", null)
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceReviews_Places_PlaceId");

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceReviews_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.PlaceTag", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Place", "Place")
                        .WithMany("Tags")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceTags_Places_PlaceId");

                    b.HasOne("LocalMateAI.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PlaceTags_Tags_TagId");

                    b.Navigation("Place");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SingleItineraryEntitlement", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("ConsumedTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocalMateAI.Domain.Entities.SingleItineraryProductVersion", null)
                        .WithMany()
                        .HasForeignKey("SingleItineraryProductVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("SourcePaymentOrderId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPeriod", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.UserSubscription", null)
                        .WithMany()
                        .HasForeignKey("LegacyUserSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanId", "PlanVersionId")
                        .HasPrincipalKey("PlanId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("SourcePaymentOrderId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocalMateAI.Domain.Entities.PaymentOrder", null)
                        .WithMany()
                        .HasForeignKey("TerminatedByOrderId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("Id", "CurrentVersionId")
                        .HasPrincipalKey("PlanId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPlanVersion", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SubscriptionPlanVersionFeature", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.PlanFeature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.SystemSetting", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Trip", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Trips_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.TripTag", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TripTags_Tags_TagId");

                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany("Tags")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TripTags_Trips_TripId");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UsageEvent", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalMateAI.Domain.Entities.SubscriptionPeriod", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionPeriodId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.User", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("LockedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LocalMateAI.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserExternalLogins_Users_UserId");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserPreferenceTag", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserPreferenceTags_Tags_TagId");

                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany("PreferenceTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPreferenceTags_Users_UserId");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("LocalMateAI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.CuratedItinerary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Place", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("LocalMateAI.Domain.Entities.User", b =>
                {
                    b.Navigation("PreferenceTags");
                });
#pragma warning restore 612, 618
        }
    }
}
