-- Đồng bộ bảng "Places" và "PlaceTags" của DB đang chạy với places.seed.json (2026-10-05).
-- Chạy lại nhiều lần vẫn cho cùng kết quả. DB mới tạo không cần script này (seed đọc places.seed.json).
-- Khớp địa điểm theo tên; giữ nguyên Id nên trip, lịch mẫu, đánh giá cũ không đổi.
-- Tag của 65 địa điểm dưới đây được đưa về ĐÚNG danh sách trong cột tags (tag gán tay khác sẽ bị bỏ).
-- (2026-10-06) Thêm mã địa điểm Google Maps và toạ độ lấy theo Google: cần chạy migration
-- AddPlaceGooglePlaceId TRƯỚC (script dùng cột "GooglePlaceId").
\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';
BEGIN;

CREATE TEMP TABLE sheet_places (
  name text PRIMARY KEY, category text, address text,
  latitude double precision, longitude double precision,
  cost_min numeric, cost_max numeric, description text, tags text[],
  google_place_id text
) ON COMMIT DROP;

INSERT INTO sheet_places VALUES
  ('Ben Thanh Market (Chợ Bến Thành)', 'CheckIn', 'Chợ Bến Thành, Lê Lai, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7725168, 106.6980208, 0, 0, 'Chợ lâu đời, đông vui và nhộn nhịp, nhiều sạp đồ lưu niệm và quầy ăn vặt. Hợp với nhóm bạn hoặc khách lần đầu tới Sài Gòn muốn dạo chơi, mua quà. Buổi trưa khá nóng và đông, đi buổi sáng dễ chịu hơn.', ARRAY['Check-in', 'Văn hóa'], 'ChIJTeYpMT8vdTERMH8sUnkta40'),
  ('Bột chiên Cô Mẽ', 'Food', '10 Phan Bội Châu, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7725982, 106.6987722, 50000, 100000, 'Quán bột chiên vỉa hè nức tiếng với đĩa bánh giòn rụm và nước tương pha vừa vị. Rất thích hợp cho bữa xế chiều ăn vặt nhẹ bụng cùng bạn bè. Quán ngồi bàn nhựa lề đường, giờ tan tầm khá đông khách.', ARRAY['Ẩm thực'], 'ChIJXYSD7lYvdTER4jfmYCRijY0'),
  ('Bánh Bèo Chợ Bến Thành', 'Food', 'Phan Chu Trinh, Bến Thành, Hồ Chí Minh 700900, Việt Nam', 10.7726528, 106.6975357, 35000, 100000, 'Quầy bánh bèo Huế gia truyền nổi tiếng với đĩa thập cẩm tôm cháy đậm đà. Điểm dừng chân ăn vặt hấp dẫn cho du khách thích ẩm thực miền Trung. Quầy nằm trong chợ, nên ghé sớm để tránh giờ trưa đông đúc.', ARRAY['Ẩm thực'], 'ChIJ0cuMyzgvdTERJNp8NfIXyzo'),
  ('Cơm tấm 182', 'Food', '182 Lê Thánh Tôn, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7730106, 106.6972222, 50000, 80000, 'Quán cơm tấm bình dân quen thuộc với miếng sườn nướng than thơm lừng đậm vị. Phù hợp nạp nhanh năng lượng cho bữa trưa văn phòng và khách tham quan. Giờ trưa quán thường chật kín, nên tranh thủ ghé sớm.', ARRAY['Ẩm thực'], 'ChIJbb11IsYvdTERkWuA6Weledk'),
  ('Local Saigon Cafe - Bến Thành', 'Cafe', '12 Thủ Khoa Huân, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7734577, 106.6975476, 45000, 80000, 'Quán cà phê phong cách hoài cổ với ban công ngắm nhìn trọn nhịp sống phố thị. Thích hợp trò chuyện nhẹ nhàng, đọc sách hoặc chụp ảnh phong cách vintage. Buổi chiều mát mẻ ngồi ban công đón gió rất thư giãn.', ARRAY['Cà phê', 'Chụp ảnh', 'Chill nhẹ'], 'ChIJ548yye0ZdTERv1ER0kMpBG4'),
  ('Soo Kafe Bến Thành', 'Cafe', '35 Phan Chu Trinh, Bến Thành, Hồ Chí Minh 70000, Việt Nam', 10.772408, 106.6972096, 60000, 95000, 'Quán cà phê tối giản nhiều mảng xanh, sở hữu ban công ngắm phố cực chill. Điểm hẹn lý tưởng để chụp ảnh check-in, hẹn hò hoặc làm việc yên tĩnh. Nên ghé buổi sáng để đón ánh sáng tự nhiên đẹp nhất.', ARRAY['Cà phê', 'Chụp ảnh', 'Chill nhẹ'], 'ChIJLUnNLj8vdTERtZ0FtgSj9-A'),
  ('Bảo tàng Mỹ thuật Thành phố Hồ Chí Minh', 'Culture', '97 Phó Đức Chính, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7699472, 106.6992162, 30000, 30000, 'Tòa dinh thự cổ thời Pháp lộng lẫy, lưu giữ nhiều tác phẩm nghệ thuật giá trị. Điểm đến văn hóa đặc sắc cho người yêu hội họa và thích chụp ảnh nghệ thuật. Bạn nên dành khoảng 1-2 tiếng để thong thả tham quan.', ARRAY['Văn hóa', 'Chụp ảnh'], 'ChIJPccxGQAvdTERYMYelqaxe8M'),
  ('Maison Marou Café Ben Thanh', 'Cafe', '144Bis Lê Thánh Tôn, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7735128, 106.6979635, 60000, 140000, 'Không gian sô-cô-la thủ công cao cấp với nhiều món bánh tráng miệng tinh tế. Hợp cho buổi hẹn hò ngọt ngào, gặp gỡ bạn bè hoặc mua sô-cô-la làm quà. Mức giá tương đối cao nhưng chất lượng bánh nước rất tương xứng.', ARRAY['Cà phê'], 'ChIJ6XR0HOUvdTERLmL3SWTk0NU'),
  ('Nhà hát Thành phố Hồ Chí Minh', 'CheckIn', '07 Công trường Lam Sơn, Sài Gòn, Hồ Chí Minh 700000, Việt Nam', 10.7766128, 106.7031715, 80000, 1750000, 'Công trình kiến trúc Pháp cổ kính tráng lệ, biểu tượng văn hóa lâu đời của Sài Gòn. Thích hợp dừng chân check-in ngoại cảnh hoặc thưởng thức các đêm nhạc kịch đỉnh cao. Buổi tối tòa nhà lên đèn lung linh, khu bậc thềm rất mát.', ARRAY['Check-in', 'Văn hóa', 'Chụp ảnh'], 'ChIJKcrnSUYvdTERO64MErYx9VU'),
  ('Café Carré', 'Cafe', '116 Nguyễn Huệ, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.7759307, 106.7021115, 95000, 3850000, 'Quán cà phê sang trọng phong cách cổ điển, nằm ngay trục đường Nguyễn Huệ sầm uất. Không gian tĩnh lặng, tinh tế, thích hợp tiếp khách hoặc trò chuyện sâu lắng. Giá thành nhỉnh hơn mặt bằng chung, đổi lại dịch vụ rất chu đáo.', ARRAY['Cà phê', 'Chill nhẹ'], 'ChIJV9ERtY8vdTERGcKC7-JI488'),
  ('Các xe quán ăn vặt nhỏ xung quanh', 'Food', '07 Công trường Lam Sơn, Sài Gòn, Hồ Chí Minh 700000, Việt Nam', 10.776791935454133, 106.70315001856433, 40000, 100000, 'Dãy xe đẩy ăn vặt bình dân với bánh tráng nướng, cá viên chiên và trà tắc thơm ngon. Điểm tụ tập ưa thích của học sinh, sinh viên ngồi hóng mát buổi tối. Bạn nên hỏi giá trước khi mua và nhớ bỏ rác đúng nơi quy định.', ARRAY['Ẩm thực'], NULL),
  ('Phố đi bộ Nguyễn Huệ', 'CheckIn', 'Nguyễn Huệ, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.774231202620333, 106.70361783102214, 0, 0, 'Quảng trường đi bộ sôi động bậc nhất trung tâm với nhiều hoạt động biểu diễn đường phố. Nơi lý tưởng để dạo mát buổi tối, chụp ảnh và cảm nhận nhịp sống hiện đại. Cuối tuần thường rất đông đúc, bạn nên chú ý bảo quản tư trang.', ARRAY['Check-in', 'Chụp ảnh'], 'ChIJnRF9v0YvdTERcuW8mp0X9us'),
  ('Dinh Độc Lập', 'CheckIn', 'Bến Thành, Hồ Chí Minh, Việt Nam', 10.7769942, 106.6953021, 40000, 60000, 'Di tích lịch sử nổi tiếng với kiến trúc thập niên 60 và bãi cỏ xanh mướt rộng lớn. Phù hợp cho du khách khám phá lịch sử, ngắm cảnh và chụp ảnh lưu niệm. Nên dành thời gian tham quan cả khu hầm chỉ huy độc đáo bên dưới.', ARRAY['Văn hóa', 'Check-in', 'Chụp ảnh'], 'ChIJL0dwVTgvdTERao3t8B1Jhxc'),
  ('Nhà thờ Đức Bà Sài Gòn', 'Culture', '01 Công trường Công xã Paris, Quận 1, Hồ Chí Minh 70000, Việt Nam', 10.7797855, 106.6990189, 0, 0, 'Công trình kiến trúc Gothic bằng gạch đỏ trứ danh, biểu tượng thân thuộc của thành phố. Điểm tham quan không thể bỏ qua để chụp ảnh kỷ niệm và ngắm kiến trúc cổ. Hiện nhà thờ đang trùng tu, du khách chủ yếu chiêm ngưỡng bên ngoài.', ARRAY['Văn hóa', 'Check-in', 'Chụp ảnh'], 'ChIJUSTY5jcvdTERRVvtbJNZT-g'),
  ('Bưu Điện Thành Phố Hồ Chí Minh', 'Culture', '80 Nguyễn Du, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.7798889, 106.7006521, 0, 0, 'Tòa bưu điện cổ nổi bật với sắc vàng Pháp, mái vòm rộng và buồng điện thoại gỗ xưa. Điểm check-in hoài cổ lý tưởng, nơi bạn có thể gửi bưu thiếp gửi tặng bạn bè. Buổi sáng ánh nắng rọi vào cửa kính mái vòm lên hình rất đẹp.', ARRAY['Văn hóa', 'Check-in', 'Chụp ảnh'], 'ChIJZ3RKEwAvdTERjqS3B3BQAM0'),
  ('Thảo Cầm Viên Sài Gòn', 'CheckIn', '2 Nguyễn Bỉnh Khiêm, Sài Gòn, Hồ Chí Minh 700000, Việt Nam', 10.7873344, 106.7050566, 60000, 60000, 'Vườn thú lâu đời xanh mát giữa lòng phố thị với hệ sinh thái động thực vật đa dạng. Thích hợp cho gia đình có trẻ nhỏ, nhóm bạn picnic hoặc chụp ảnh cổ điển. Nên đi vào sáng sớm mát mẻ để thấy các loài thú hoạt động nhiều.', ARRAY['Check-in', 'Thiên nhiên', 'Chill nhẹ', 'Chụp ảnh'], 'ChIJx7wwM0svdTERjuH2a9dkuU0'),
  ('Bảo tàng Lịch sử Thành phố Hồ Chí Minh', 'Culture', '2 Nguyễn Bỉnh Khiêm, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.788075, 106.7047291, 30000, 30000, 'Nơi trưng bày hàng ngàn cổ vật quý, tái hiện dòng chảy lịch sử văn hóa dân tộc. Điểm đến bổ ích cho các bạn trẻ và du khách yêu thích tìm hiểu lịch sử. Nằm sát Thảo Cầm Viên nên rất tiện kết hợp tham quan trong cùng buổi.', ARRAY['Văn hóa'], 'ChIJ5fqrRUsvdTERlfW0JX8JGyU'),
  ('Công viên gầm cầu Ba Son', 'CheckIn', 'Dưới gầm cầu Ba Son (Cầu Thủ Thiêm 2)', 10.78088, 106.7082155, 0, 0, 'Khuôn viên bờ sông thoáng đãng với góc ngắm nhìn toàn cảnh Landmark 81 cực đẹp. Điểm tụ tập hóng gió đêm quen thuộc của giới trẻ sau giờ học, giờ làm. Nên ghé lúc hoàng hôn buông xuống để chụp được những bức hình ngược sáng.', ARRAY['Check-in', 'Thiên nhiên', 'Chill nhẹ', 'Chụp ảnh'], 'ChIJC7NGMbAvdTERhuxfbpmwkQc'),
  ('Đường sách Thành phố Hồ Chí Minh', 'CheckIn', '2 Đ. Nguyễn Văn Bình, Sài Gòn, Hồ Chí Minh 700000, Việt Nam', 10.780963, 106.7000734, 0, 0, 'Không gian rợp bóng cây mát rượi với nhiều gian hàng sách và quán cà phê thanh lịch. Nơi lý tưởng để tản bộ, chọn mua những cuốn sách hay và thư giãn tâm hồn. Cuối tuần ở đây thường có nhiều triển lãm tranh ảnh và giao lưu tác giả.', ARRAY['Văn hóa', 'Check-in', 'Chill nhẹ'], 'ChIJS8Yv1zcvdTERUI2V47UxkPw'),
  ('Công viên Tao Đàn', 'CheckIn', 'Bến Thành, Hồ Chí Minh 700000, Việt Nam', 10.7755796, 106.6920797, 0, 0, 'Lá phổi xanh yên bình với hàng cây cổ thụ cao rợp bóng và đường đi bộ râm mát. Phù hợp tập thể dục buổi sáng, tản bộ ngắm cảnh hoặc ngồi đọc sách thư giãn. Sáng sớm ở góc công viên thường có hội chim hót tụ họp rất vui tai.', ARRAY['Thiên nhiên', 'Chill nhẹ'], 'ChIJsXOVajkvdTERcBdP0Xow8j4'),
  ('Phố đi bộ Bùi Viện', 'Culture', 'Bùi Viện Phạm Ngũ Lão, phường, Bến Thành, Hồ Chí Minh, Việt Nam', 10.767351, 106.6938836, 0, 0, 'Con phố Tây náo nhiệt thâu đêm với âm nhạc sôi động và các quán bia lề đường. Điểm đến hấp dẫn cho ai muốn hòa mình vào không khí giải trí đêm đa văn hóa. Phố đông đúc nhất từ 20h trở đi, bạn chú ý cẩn thận tài sản cá nhân.', ARRAY['Check-in', 'Văn hóa'], 'ChIJCdzLBRYvdTERpsMyNScNwPE'),
  ('Công viên 23/9', 'CheckIn', 'Bến Thành, Hồ Chí Minh, Việt Nam', 10.7687114, 106.69234, 0, 0, 'Khoảng không gian xanh rộng lớn trải dài, kết nối chợ Bến Thành và khu phố Tây. Nơi tụ họp quen thuộc của sinh viên giao lưu tiếng Anh, tập nhảy và dạo mát. Buổi chiều tối không khí thoáng đãng, thích hợp ngồi ghế đá trò chuyện.', ARRAY['Thiên nhiên', 'Chill nhẹ'], 'ChIJu4YK_j4vdTERfSn0egKOyug'),
  ('Saigon Centre', 'CheckIn', '65 - 67 Lê Lợi, Sài Gòn, Hồ Chí Minh 71016, Việt Nam', 10.7731031, 106.70105, 0, 0, 'Trung tâm thương mại hiện đại quy tụ nhiều thương hiệu quốc tế và khu Takashimaya sầm uất. Điểm đến tuyệt vời để mua sắm, check-in sang chảnh và tránh nóng ngày hè. Khu ẩm thực dưới tầng hầm có rất nhiều món ngon châu Á để lựa chọn.', ARRAY['Check-in', 'Ẩm thực'], 'ChIJPY9kQ0cvdTERNEixjJGVzhY'),
  ('Lacàph Coffee', 'Cafe', '151 Đồng Khởi, Sài Gòn, Hồ Chí Minh, Vietnam', 10.7757628, 106.7031707, 50000, 100000, 'Không gian cà phê đương đại tôn vinh hạt nông sản Việt qua các công thức sáng tạo. Rất hợp cho người sành cà phê, khách bàn công việc hoặc trải nghiệm văn hóa mới. Bạn nên thử các món pha từ hạt Robusta lên men mang hương vị rất riêng.', ARRAY['Cà phê'], 'ChIJm-gZAiUvdTERF1P6ptacTwc'),
  ('Tonkin Specialty Coffee', 'Cafe', '91 Lý Tự Trọng, Bến Thành, Hồ Chí Minh 700000, Việt Nam', 10.7743893, 106.6978901, 49000, 89000, 'Quán cà phê phong cách Indochine ấm cúng với nền nhạc jazz nhẹ nhàng và nội thất gỗ mộc. Lựa chọn tuyệt vời để tìm góc yên tĩnh đọc sách, làm việc hoặc chuyện trò. Đừng quên nếm thử món cà phê trứng béo thơm đặc trưng của quán.', ARRAY['Cà phê', 'Chill nhẹ'], 'ChIJzaevQMcvdTERYE3UhLKg5NE'),
  ('Bếp Mẹ Ỉn', 'Food', '136/9 Lê Thánh Tôn, Bến Thành, Hồ Chí Minh, Việt Nam', 10.7738567, 106.6980798, 89000, 279000, 'Quán ăn ấm cúng trong ngõ nhỏ, chuyên phục vụ mâm cơm nhà và món ăn dân dã Việt Nam. Phù hợp cho bữa ăn gia đình ấm cúng hoặc dẫn bạn bè nước ngoài trải nghiệm. Món bánh xèo tôm nhảy và cơm chiên trái dừa là hai món rất nên thử.', ARRAY['Ẩm thực'], 'ChIJcwyUxjgvdTERFwXMvGKDY0U'),
  ('Pizza 4P''s Estella Place', 'Food', 'TTTM Estella Place, 88 Song Hành, Bình Trưng, Hồ Chí Minh 70000, Vietnam', 10.8018374, 106.7484399, 200000, 800000, 'Nhà hàng ẩm thực Ý phong cách Nhật nổi tiếng với pizza nướng củi và phô mai tự làm. Không gian lịch sự, ấm cúng, rất thích hợp cho tiệc gia đình hoặc hẹn hò. Quán thường kín bàn vào cuối tuần nên bạn hãy nhớ đặt trước qua mạng.', ARRAY['Ẩm thực'], 'ChIJAZp7s5sndTERvNeCZICxzWY'),
  ('Bến Bạch Đằng', 'CheckIn', '2 Tôn Đức Thắng, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.77601580483109, 106.7072074693158, 15000, 30000, 'Bến tàu công viên ven sông thoáng đãng, nơi đón các chuyến tàu buýt đường sông Waterbus. Rất hợp để đi dạo hóng gió, ngắm hoàng hôn lãng mạn trên mặt sông Sài Gòn. Nên trải nghiệm đi một chuyến buýt sông chiều muộn ngắm phố lên đèn.', ARRAY['Check-in', 'Thiên nhiên', 'Chill nhẹ', 'Chụp ảnh'], NULL),
  ('CieL Dining', 'Food', '6/3, Đ. Số 50, An Khánh, Hồ Chí Minh, Vietnam', 10.8048085, 106.7334666, 1000000, 5000000, 'Nhà hàng ẩm thực fine dining nổi bật với thực đơn tasting kết hợp kỹ thuật Pháp tinh tế. Điểm hẹn đẳng cấp cho những dịp kỷ niệm quan trọng, tiệc hẹn hò lãng mạn. Trải nghiệm dịch vụ chuyên nghiệp cùng các món ăn biến tấu theo mùa.', ARRAY['Ẩm thực'], 'ChIJ15AVEwAndTER67Ng7TJICpE'),
  ('Landmark 81', 'CheckIn', '720A Điện Biên Phủ, Phường, Thạnh Mỹ Tây, Hồ Chí Minh 72300, Vietnam', 10.7951153, 106.7221002, 0, 0, 'Tòa tháp cao nhất Việt Nam biểu trưng cho bó tre, tích hợp đài quan sát SkyView và TTTM. Điểm đến lý tưởng để ngắm toàn cảnh Sài Gòn từ trên cao, mua sắm và vui chơi. Bạn có thể kết hợp dạo mát tại công viên bờ sông rộng lớn ngay bên cạnh.', ARRAY['Check-in', 'Chụp ảnh'], 'ChIJEQnz-MIndTERzRrJ-HNQrDY'),
  ('Ănăn Saigon', 'Food', 'QPC3+M6Q, 89 Tôn Thất Đạm, Sài Gòn, Hồ Chí Minh 000000, Việt Nam', 10.771729, 106.702893, 1200000, 3800000, 'Nhà hàng đạt sao Michelin, biến tấu món ăn đường phố Việt Nam thành ẩm thực cao cấp. Trải nghiệm độc đáo cho tín đồ ẩm thực muốn khám phá hương vị Việt sáng tạo. Bạn cần đặt bàn trước khá sớm và chuẩn bị ngân sách cho bữa ăn sang trọng.', ARRAY['Ẩm thực'], 'ChIJZ_dpJ0EvdTER5wOl-TLvN-8'),
  ('Bảo tàng Tôn Đức Thắng', 'Culture', '5 Tôn Đức Thắng, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.7773163, 106.7065242, 0, 0, 'Không gian lưu giữ trang trọng các hiện vật, hình ảnh về cuộc đời Bác Tôn bên bờ sông Son. Điểm đến giàu ý nghĩa cho du khách muốn tìm hiểu lịch sử đấu tranh cách mạng. Vị trí nằm ngay sát ga Ba Son, thuận tiện kết hợp đi dạo công viên bến tàu.', ARRAY['Văn hóa'], 'ChIJ9aHU7UUvdTERwvaHOXtRzVI'),
  ('Cà phê Bệt Nhà Thờ Đức Bà', 'Cafe', '1 Công trường Công xã Paris, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.779023966391753, 106.69922208702619, 30000, 100000, 'Nét văn hóa vỉa hè đặc trưng của giới trẻ Sài Gòn chỉ với vài tờ báo và ly trà sữa, cà phê. Không gian mộc mạc, thoáng mát, thích hợp ngồi ngắm đường phố và trò chuyện rôm rả. Buổi sáng cuối tuần là thời điểm thư thái nhất để ghé trải nghiệm.', ARRAY['Cà phê', 'Chill nhẹ'], NULL),
  ('Bảo tàng Chứng tích Chiến tranh', 'Culture', 'Phường 6, Quận 3, Hồ Chí Minh 700000, Việt Nam', 10.7795106, 106.6920916, 20000, 300000, 'Bảo tàng lịch sử lưu giữ tư liệu, hiện vật chân thực về hậu quả của chiến tranh tại Việt Nam. Điểm tham quan sâu sắc thu hút nhiều du khách trong và ngoài nước chiêm nghiệm. Không gian mang tính lịch sử lắng đọng, bạn nên dành ít nhất 1 giờ tham quan.', ARRAY['Văn hóa'], 'ChIJzwg3ojAvdTERqnQUK99K2Xw'),
  ('Vinhome Golden River Bason', 'CheckIn', 'Aqua 3, 2 Tôn Đức Thắng, Sài Gòn, Hồ Chí Minh, Việt Nam', 10.7868813, 106.7115181, 0, 0, 'Khu đô thị sinh thái hiện đại sở hữu đường dạo bộ ven sông thoáng mát và bến du thuyền. Nơi lý tưởng để chạy bộ thể dục, hóng gió sông và chụp ảnh phong cách hiện đại. Khuôn viên nội khu sạch đẹp, buổi tối ánh đèn phản chiếu mặt sông rất thơ mộng.', ARRAY['Check-in', 'Thiên nhiên', 'Chill nhẹ', 'Chụp ảnh'], 'ChIJfXXk_7ovdTERDpc49LAwdwI'),
  ('Pearl Center - Thảo Điền Pearl', 'CheckIn', '12 Quốc Hương, An Khánh, Hồ Chí Minh 700900, Việt Nam', 10.8012804, 106.7328725, 0, 0, 'Trung tâm thương mại tích hợp rạp chiếu phim, siêu thị và nhiều nhà hàng tiện lợi. Phục vụ nhu cầu giải trí, ăn uống nhanh chóng cho cư dân và du khách khu Thảo Điền. Vị trí kết nối thẳng cụm ga metro, rất tiện dừng chân nghỉ ngơi giữa hành trình.', ARRAY['Check-in', 'Ẩm thực'], 'ChIJ69WzURomdTERTP98e9_pRco'),
  ('Khu du lịch Tân Cảng', 'Food', 'A100 Đ. Ung Văn Khiêm, Thạnh Mỹ Tây, Hồ Chí Minh, Việt Nam', 10.7999642, 106.7247441, 60000, 350000, 'Khu ẩm thực nghỉ dưỡng ven sông rợp bóng cây với các nhà hàng bờ sông thoáng đãng. Rất thích hợp cho các buổi liên hoan gia đình, họp lớp hoặc tiệc công ty. Bạn có thể vừa thưởng thức món ngon vừa đón gió sông Sài Gòn mát rượi.', ARRAY['Ẩm thực', 'Thiên nhiên', 'Chill nhẹ'], 'ChIJow37ah0mdTER16pHqnlbEV0'),
  ('Tam Sơn Yachting (Bến Du Thuyền Vinhomes Central)', 'CheckIn', '208 Nguyễn Hữu Cảnh, Thạnh Mỹ Tây, Hồ Chí Minh, Việt Nam', 10.7956074, 106.725052, 0, 0, 'Bến du thuyền sang trọng chuẩn quốc tế bên bờ sông với góc chụp ảnh thời thượng. Điểm check-in đẳng cấp mang phong cách hiện đại cho du khách và giới trẻ. Nằm sát mép công viên bờ sông, ngắm hoàng hôn buông xuống đây cực kỳ thơ mộng.', ARRAY['Check-in', 'Chụp ảnh'], 'ChIJr9UeI70ndTERG1yHM4vWWYo'),
  ('IDOL Quán', 'Food', '25/6A Đ. số 17, Thủ Đức, Hồ Chí Minh, Việt Nam', 10.860436, 106.7874134, 49000, 119000, 'Quán lẩu nướng bình dân sôi động với thực đơn món ăn đa dạng và bia giải khát. Điểm tụ họp lý tưởng sau giờ học, giờ làm cho sinh viên và nhóm bạn bè. Giá cả sinh viên rất phải chăng, quán đông vui nhất vào các tối cuối tuần.', ARRAY['Ẩm thực'], 'ChIJAQAAAGUndTERJ0_xc4ZkZo0'),
  ('Tô Tượng Thủ Đức - Tiệm Nhà Moon', 'CheckIn', '66 Đ. số 17, Linh Xuân, Hồ Chí Minh 700000, Việt Nam', 10.8610141, 106.7879204, 20000, 90000, 'Không gian xưởng tô tượng sáng tạo với hàng trăm mẫu tượng thạch cao độc đáo. Nơi thư giãn nhẹ nhàng, phù hợp cho các cặp đôi hẹn hò hoặc nhóm bạn xả stress. Tiệm chuẩn bị sẵn đầy đủ màu vẽ, bạn chỉ cần thỏa sức sáng tạo tác phẩm.', ARRAY['Check-in', 'Chill nhẹ'], 'ChIJ4cttQhQndTERgboulBNg1zA'),
  ('Bò Né Chibi (Beefsteak)', 'Food', 'Đ. số 17/7 Kp. 38, P, Linh Xuân, Hồ Chí Minh, Việt Nam', 10.8598587, 106.7885173, 33000, 67000, 'Quán bò né chảo gang thơm phức với miếng bò mềm, trứng ốp la và pate béo ngậy. Lựa chọn tuyệt vời cho bữa sáng nhiều năng lượng hoặc bữa trưa nhanh gọn. Món dọn kèm bánh mì nóng giòn và đĩa salad dầu giấm chua ngọt vừa miệng.', ARRAY['Ẩm thực'], 'ChIJj4wT51bZdDEREmvxE-m6WQ8'),
  ('METROO COFFEE', 'Cafe', '513 Song Hành Xa Lộ Hà Nội, Linh Xuân, Hồ Chí Minh 70000, Việt Nam', 10.859099, 106.7885179, 22000, 50000, 'Quán cà phê máy lạnh phong cách tối giản với view ngắm tuyến tàu điện metro. Thích hợp cho các bạn sinh viên ngồi học bài, chạy đồ án hoặc gặp gỡ đối tác. Quán có ổ cắm điện đầy đủ cùng wifi tốc độ cao, phục vụ nước uống cả ngày.', ARRAY['Cà phê'], 'ChIJxSzvOAAndTERUhQ6ijSMteE'),
  ('Next Step Coffee', 'Cafe', '501 Song Hành Xa Lộ Hà Nội, Linh Xuân, Hồ Chí Minh, Việt Nam', 10.858897, 106.788113, 17000, 49000, 'Quán cà phê trẻ trung hiện đại phục vụ các dòng cà phê máy và trà thanh mát. Phù hợp làm trạm dừng nạp năng lượng nhanh cho sinh viên và dân công sở. Đồ uống giá hạt dẻ, không gian sạch sẽ thoáng mát rất tiện ghé mua mang đi.', ARRAY['Cà phê'], 'ChIJRZsXPgAndTER-Mo6HMqXXwI'),
  ('Tiệm bánh nhà Vi', 'Food', '18/113 tổ 8, khu phố 6, Linh Xuân, Hồ Chí Minh, Việt Nam', 10.8669332, 106.7991153, 25000, 100000, 'Tiệm bánh ngọt nhỏ xinh quen thuộc của sinh viên Làng Đại học với đa dạng món bánh. Phù hợp cho những buổi hẹn hò ăn vặt nhẹ nhàng hoặc mua bánh kem tặng bạn bè. Bánh bông lan trứng muối và trà sữa ở tiệm có giá rất mềm, vị vừa miệng.', ARRAY['Ẩm thực', 'Chill nhẹ'], 'ChIJDdszaAYndTERzDxP47gOH24'),
  ('Cơm Gà Xối Mỡ Nghĩa Ký', 'Food', 'VQCX+J67, Đường Trục Chính 10, Linh Xuân, Hồ Chí Minh, Việt Nam', 10.871449, 106.7979649, 25000, 40000, 'Quán cơm gà bình dân trứ danh với góc đùi gà xối mỡ giòn rụm và cơm rang đỏ. Điểm ăn trưa lý tưởng để nạp nhanh năng lượng cho sinh viên và du khách. Đĩa cơm đầy đặn kèm canh nóng hổi, giá cả rất vừa túi tiền mọi đối tượng.', ARRAY['Ẩm thực'], 'ChIJlbeHTgDZdDERN2IueEQIYMk'),
  ('Cà Phê Chú Vũ', 'Cafe', '16/21 khu phố 33, Linh Xuân, Hồ Chí Minh, Việt Nam', 10.8716423, 106.7978859, 15000, 25000, 'Quán cà phê sân vườn mộc mạc đậm chất sinh viên khu Đại học Quốc gia. Không gian yên bình, thoáng đãng, thích hợp ngồi học bài hoặc chơi cờ thư giãn. Giá đồ uống bình dân, không khí sớm mai trong lành mang lại cảm giác dễ chịu.', ARRAY['Cà phê', 'Chill nhẹ'], 'ChIJ8eTPJ43ZdDERbcaYqwkuti4'),
  ('Napoli Pizza', 'Food', '2a Hàn Thuyên, Thủ Đức, Hồ Chí Minh, Việt Nam', 10.8460348, 106.7706111, 59000, 189000, 'Quán pizza phong cách Ý với đế bánh nướng giòn thơm cùng phô mai béo ngậy. Lựa chọn tuyệt vời cho các buổi tiệc sinh nhật bạn bè hoặc bữa ăn gia đình. Mức giá khá mềm, món mỳ Ý xốt bò bằm và pizza thập cẩm rất được ưa chuộng.', ARRAY['Ẩm thực'], 'ChIJ7SnTGQAndTERZdDADdhqOgc'),
  ('Công viên văn hóa Suối Tiên', 'CheckIn', '120 Song Hành Xa Lộ Hà Nội, Tăng Nhơn Phú, Hồ Chí Minh 70000, Việt Nam', 10.8661863, 106.8031678, 80000, 150000, 'Công viên giải trí văn hóa lịch sử lâu đời với nhiều trò chơi dưới nước hấp dẫn. Thích hợp cho gia đình có trẻ nhỏ và nhóm bạn trẻ vui chơi trọn ngày. Bạn nên chuẩn bị nón dù che nắng và đồ bơi để trải nghiệm biển Tiên Đồng.', ARRAY['Check-in', 'Văn hóa'], 'ChIJDXlfx1sndTERFg6NcPqJ8e8'),
  ('Metro Coffee - Suối Tiên', 'Cafe', '1 Số 13, Đông Hòa, Hồ Chí Minh, Việt Nam', 10.8787351, 106.8135781, 20000, 45000, 'Quán cà phê trạm dừng chân hiện đại với tầm nhìn hướng thẳng tuyến metro trên cao. Không gian thoải mái, tiện nạp năng lượng và chờ đón chuyến tàu tiếp theo. Đồ uống có mức giá bình dân, sáng sớm ghé mua ly cà phê mang đi rất tiện.', ARRAY['Cà phê'], 'ChIJwR-uc6YldTERWbUZerwGopg'),
  ('Là gốm', 'CheckIn', '02 Nguyễn Bỉnh Khiêm, Thủ Đức, Hồ Chí Minh, Việt Nam', 10.8467398, 106.7710356, 100000, 250000, 'Xưởng gốm thủ công mộc mạc yên bình, nơi tự tay nhào nặn đồ gốm xinh xắn. Trải nghiệm thư giãn tâm trí mới lạ dành cho các cặp đôi hoặc nhóm bạn sáng tạo. Có thợ hướng dẫn tận tình từng bước, bạn sẽ được mang thành phẩm nung về nhà.', ARRAY['Check-in', 'Chill nhẹ'], 'ChIJY2EjWBkndTER_4kcfI70Cqw'),
  ('THE TERMINAL Nhà hàng món Âu', 'Food', '3 Nguyễn Công Trứ, Thủ Đức, Hồ Chí Minh 71306, Việt Nam', 10.8471918, 106.7711351, 65000, 380000, 'Nhà hàng món Âu phong cách hiện đại với món bít tết hảo hạng và mỳ Ý chuẩn vị. Không gian tinh tế, lãng mạn, rất thích hợp cho các buổi hẹn hò hoặc kỷ niệm. Quán phục vụ chu đáo, bạn có thể gọi thêm ly rượu vang nhẹ để tối thêm trọn vẹn.', ARRAY['Ẩm thực'], 'ChIJl92uo04ndTERV9zovchaVe4'),
  ('Xoài Thái Kitchen', 'Food', '6/3, Đ. Số 3, Thủ Đức, Hồ Chí Minh, Việt Nam', 10.8350787, 106.7644342, 30000, 180000, 'Quán ẩm thực Thái Lan chuẩn vị với các món gỏi đu đủ và lẩu tomyum chua cay. Điểm hẹn ăn uống hấp dẫn cho nhóm bạn trẻ yêu thích các món ăn Chùa Vàng. Không gian quán gần gũi, các món xóc xốt thái đậm vị rất hợp nhâm nhi.', ARRAY['Ẩm thực'], 'ChIJtX5SewAndTERBu5w1p8eiig'),
  ('Chạm Rooftop', 'Cafe', '99 Trần Thị Điệu, Phước Long, Hồ Chí Minh, Việt Nam', 10.8311988, 106.7696911, 39000, 129000, 'Quán bia rooftop lộng gió trên tầng thượng với góc ngắm hoàng hôn cực chill. Lựa chọn tuyệt vời cho các buổi hẹn hò lãng mạn hoặc tụ tập bạn bè cuối tuần. Bạn nên ghé quán từ 17h30 chiều để bắt trọn khoảnh khắc ráng chiều buông.', ARRAY['Cà phê', 'Chill nhẹ', 'Chụp ảnh'], 'ChIJiXjoiwondTERUTcyGSQ9lEE'),
  ('Homes sushi', 'Food', '86e Trần Thị Điệu, Phước Long, Hồ Chí Minh, Việt Nam', 10.8321913, 106.7698048, 25000, 250000, 'Quán ẩm thực Nhật Bản bình dân nổi tiếng với sushi tươi ngon và lát cá béo ngậy. Rất hợp cho các bạn sinh viên hoặc gia đình muốn đổi vị ngon miệng. Quán có không gian ấm cúng, nên đặt bàn trước vào buổi tối để tránh chờ lâu.', ARRAY['Ẩm thực'], 'ChIJJ7Xz0vIndTERp3clJajavaQ'),
  ('The Vibes Events & Dining', 'Food', '51bis An Phú, An Khánh, Hồ Chí Minh, Việt Nam', 10.8085856, 106.7506565, 85000, 550000, 'Tổ hợp nhà hàng sân vườn xanh mát kết hợp không gian ẩm thực sang trọng. Điểm hẹn đẳng cấp cho tiệc gia đình, gặp gỡ đối tác hoặc tổ chức sinh nhật. Thực đơn kết hợp Á - Âu tinh tế, cảnh quan về đêm lên đèn lung linh rất đẹp.', ARRAY['Ẩm thực'], 'ChIJ-z1PLPgndTERk-VwdZ9-las'),
  ('Huyền coffee&Tea', 'Cafe', '2 Đường 2, KP1, An Khánh, Hồ Chí Minh 12345, Việt Nam', 10.8081094, 106.7548522, 18000, 40000, 'Quán nước sân vườn mộc mạc thoáng mát với menu trà trái cây và cà phê đậm đà. Điểm dừng chân chuyện trò thân mật cùng bạn bè hoặc ngồi thư giãn hóng gió. Mức giá đồ uống rất bình dân, cô chủ quán thân thiện và phục vụ nhanh nhẹn.', ARRAY['Cà phê', 'Chill nhẹ'], 'ChIJsbCaIQAndTERiNFkJbSSvYs'),
  ('Rach Chiec Bridge Park', 'CheckIn', 'RQ74+384, An Khánh, Hồ Chí Minh, Việt Nam', 10.8126404, 106.7558227, 0, 0, 'Khuôn viên công viên ven sông thoáng đãng với góc ngắm toàn cảnh cầu Rạch Chiếc. Nơi lý tưởng để dạo bộ tập thể dục buổi chiều, hóng mát và chụp ảnh đón gió. Buổi tối không khí ven sông lộng gió, thích hợp ngồi ghế đá thư giãn sau giờ làm.', ARRAY['Thiên nhiên', 'Chill nhẹ', 'Chụp ảnh'], 'ChIJmWhaFHgndTER6LHOm6zV1cs'),
  ('MM Mega Market An Phú', 'Food', 'Khu B, Khu đô thị An Phú An Khánh, Bình Trưng, Hồ Chí Minh 700000, Việt Nam', 10.8002009, 106.7432144, 0, 0, 'Đại siêu thị sỉ lẻ sầm uất với bạt ngàn thực phẩm tươi sống và quầy ăn uống. Phù hợp cho gia đình mua sắm cuối tuần hoặc nhóm bạn ghé mua đồ picnic. Siêu thị rất rộng, bạn nên mang theo áo khoác nhẹ khi vào khu đông lạnh.', ARRAY['Ẩm thực'], 'ChIJH6-CURImdTERX2oCqYyod5Q'),
  ('Á CHÂU DIMSUM HOUSE', 'Food', '90-92 Đường Số 15, Khu đô thị An Phú An Khánh, Thủ Đức, Hồ Chí Minh 70000, Việt Nam', 10.7977391, 106.7415619, 35000, 220000, 'Nhà hàng điểm tâm Quảng Đông chuẩn vị với menu há cảo và bánh bao nóng hổi. Thích hợp cho bữa sáng sum họp gia đình hoặc buổi tụ họp ẩm thực ấm cúng. Món chân gà tàu xì và xíu mại trứng muối ở đây rất đậm đà, đáng để thử.', ARRAY['Ẩm thực'], 'ChIJZ4-OdTAndTER6WPwRQ8srQc'),
  ('Công viên Vinhomes Central Park', 'CheckIn', 'Trần Trọng Kim, Vinhomes Tân Cảng, Thạnh Mỹ Tây, Hồ Chí Minh, Việt Nam', 10.7934308, 106.7243981, 0, 0, 'Đại công viên ven sông rộng lớn với bãi cỏ xanh mướt và khu vườn Nhật cầu đỏ. Điểm picnic, chụp hình check-in và dạo bộ ngoài trời tuyệt vời cho mọi lứa tuổi. Nên ghé vào tầm hoàng hôn đến tối để ngắm tháp Landmark 81 rực rỡ ánh đèn.', ARRAY['Check-in', 'Thiên nhiên', 'Chill nhẹ', 'Chụp ảnh'], 'ChIJyS548sYndTERx_fKlYIochM'),
  ('Tháp quan sát Vinhomes Central Park', 'CheckIn', 'QPVG+65J, Vinhomes Tân Cảng, Thạnh Mỹ Tây, Hồ Chí Minh, Việt Nam', 10.7934365, 106.7254665, 0, 0, 'Đài quan sát trên cao độc đáo mang lại tầm nhìn toàn cảnh 360 độ về thành phố. Trải nghiệm khó quên cho du khách chiêm ngưỡng Sài Gòn phồn hoa từ trời cao. Bạn nên lên đài quan sát vào lúc chập tối để ngắm biển đèn lung linh tuyệt đẹp.', ARRAY['Check-in', 'Chụp ảnh'], 'ChIJtXOdcwAndTERRDYVB3RupsY'),
  ('Vincom Plaza Thủ Đức', 'CheckIn', '216 Đ. Võ Văn Ngân, Thủ Đức, Hồ Chí Minh 70000, Việt Nam', 10.8501, 106.7651, 0, 0, 'Trung tâm thương mại sôi động bậc nhất khu Đông tích hợp rạp chiếu phim và mua sắm. Điểm vui chơi, giải trí và tránh nóng quen thuộc cho giới trẻ cùng gia đình nhỏ. Các tầng tập trung nhiều thương hiệu ẩm thực, cà phê nổi tiếng tha hồ khám phá.', ARRAY['Check-in', 'Ẩm thực'], 'ChIJe0eA_KEndTERr0rIc3pPlGI'),
  ('Vincom Plaza Lê Văn Việt', 'CheckIn', '50 Đ. Lê Văn Việt, Tăng Nhơn Phú, Hồ Chí Minh 71206, Việt Nam', 10.8449727, 106.7786146, 0, 0, 'Trung tâm mua sắm và giải trí tiện nghi trên trục đường sầm uất tại Thủ Đức. Nơi tụ họp ăn uống, xem phim cuối tuần lý tưởng cho cư dân và sinh viên lân cận. Khu ẩm thực phong phú với nhiều chuỗi lẩu nướng, gà rán quen thuộc tha hồ chọn.', ARRAY['Check-in', 'Ẩm thực'], 'ChIJ7ZttRWAndTERsTa2pg4Ddac'),
  ('Khu du lịch Văn Thánh', 'Food', '48/10 Điện Biên Phủ, Thạnh Mỹ Tây, Hồ Chí Minh, Việt Nam', 10.7987213, 106.7165604, 50000, 300000, 'Ốc đảo xanh yên ả giữa lòng phố thị với hồ sen, rặng tre và bãi cỏ xanh mướt. Điểm hẹn nghỉ dưỡng cuối tuần lý tưởng để cắm trại picnic hoặc ăn món quê. Cuối tuần ở đây thường có tiệc buffet ẩm thực ba miền rất phong phú và ngon miệng.', ARRAY['Ẩm thực', 'Thiên nhiên', 'Chill nhẹ'], 'ChIJV8BHDV0pdTERvGqxdSId_50'),
  ('Pearl Plaza', 'CheckIn', '561A Điện Biên Phủ, Thạnh Mỹ Tây, Hồ Chí Minh 700000, Việt Nam', 10.7999596, 106.718563, 0, 0, 'Khu phức hợp thương mại hiện đại tích hợp siêu thị, phòng gym và rạp chiếu phim. Điểm đến thuận tiện để mua sắm, xem phim giải trí và ăn uống đa dạng món ngon. Nằm sát trạm metro Văn Thánh, rất tiện dừng chân dạo chơi giữa lịch trình.', ARRAY['Check-in', 'Ẩm thực'], 'ChIJ8zhXhNcpdTERR0mLvAon2G8');

-- 1. Địa điểm đã có: cập nhật mô tả, giá, địa chỉ, loại, toạ độ, mã Google Maps.
UPDATE "Places" p
SET "Description" = s.description,
    "Address" = s.address,
    "Category" = s.category,
    "EstimatedCostMin" = s.cost_min,
    "EstimatedCostMax" = s.cost_max,
    "Location" = ST_SetSRID(ST_MakePoint(s.longitude, s.latitude), 4326),
    "GooglePlaceId" = s.google_place_id,
    "UpdatedAt" = now()
FROM sheet_places s
WHERE p."Name" = s.name
  AND p."DeletedAt" IS NULL
  AND (p."Description", p."Address", p."Category", p."EstimatedCostMin", p."EstimatedCostMax",
       ST_X(p."Location"), ST_Y(p."Location"), p."GooglePlaceId")
      IS DISTINCT FROM (s.description, s.address, s.category, s.cost_min, s.cost_max,
       s.longitude, s.latitude, s.google_place_id);

-- 2. Địa điểm mới: thêm với trạng thái Active (giống seed).
INSERT INTO "Places" ("Id", "Name", "Description", "Address", "Location", "Category", "Status",
                      "EstimatedCostMin", "EstimatedCostMax", "IsVerified", "GooglePlaceId",
                      "CreatedAt", "UpdatedAt")
SELECT gen_random_uuid(), s.name, s.description, s.address,
       ST_SetSRID(ST_MakePoint(s.longitude, s.latitude), 4326), s.category, 'Active',
       s.cost_min, s.cost_max, false, s.google_place_id, now(), now()
FROM sheet_places s
WHERE NOT EXISTS (SELECT 1 FROM "Places" p WHERE p."Name" = s.name);

-- 3. Tag: bỏ tag không còn trong danh sách, rồi thêm tag còn thiếu.
DELETE FROM "PlaceTags" pt
USING "Places" p, sheet_places s
WHERE pt."PlaceId" = p."Id"
  AND p."Name" = s.name
  AND pt."TagId" NOT IN (SELECT t."Id" FROM "Tags" t WHERE t."Name" = ANY (s.tags));

INSERT INTO "PlaceTags" ("PlaceId", "TagId")
SELECT p."Id", t."Id"
FROM sheet_places s
JOIN "Places" p ON p."Name" = s.name
CROSS JOIN LATERAL unnest(s.tags) AS wanted(tag_name)
JOIN "Tags" t ON t."Name" = wanted.tag_name
ON CONFLICT DO NOTHING;

SELECT count(*) AS places,
       count(*) FILTER (WHERE "Status" = 'Active' AND "DeletedAt" IS NULL) AS active,
       count(DISTINCT "Name") AS distinct_names,
       (SELECT count(*) FROM "PlaceTags") AS place_tags
FROM "Places";

COMMIT;
